<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LOGINEmail AddressPasswordForgot Passwo_47530d</name>
   <tag></tag>
   <elementGuidId>2dbd4c4c-e80d-45a0-8590-ecbdbcdb06bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root-7010.jss7011.jss1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2bd97f9-d036-4624-8d00-b35bacb71846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root-7010 jss7011 jss1</value>
      <webElementGuid>0cb0d048-3889-492f-8b0d-132e3a9f6dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGINEmail Address​Password​Forgot Password ?Sign InBy logging in, you are agree to our Privacy Policy also Terms and ConditionsDon't have a company account?RegisterCopyright 2020 ©  PT Smooets Teknologi Outsourcing</value>
      <webElementGuid>b196db35-1990-4c16-a274-a24b4cfb4b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/main[@class=&quot;MuiContainer-root-6974 containerBanner MuiContainer-maxWidthLg-6980&quot;]/div[@class=&quot;MuiPaper-root-6982 paperBanner MuiPaper-elevation1-6986 MuiPaper-rounded-6983&quot;]/div[@class=&quot;MuiBox-root-7010 jss7011 jss1&quot;]</value>
      <webElementGuid>7e840995-78d5-4934-88fa-18d7e078f2d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div</value>
      <webElementGuid>14cf5f86-a199-4a94-ad61-71cb87a57d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div</value>
      <webElementGuid>b62b71b2-45ed-4586-9cfc-b5d3f9b85c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;LOGINEmail Address​Password​Forgot Password ?Sign InBy logging in, you are agree to our Privacy Policy also Terms and ConditionsDon&quot; , &quot;'&quot; , &quot;t have a company account?RegisterCopyright 2020 ©  PT Smooets Teknologi Outsourcing&quot;) or . = concat(&quot;LOGINEmail Address​Password​Forgot Password ?Sign InBy logging in, you are agree to our Privacy Policy also Terms and ConditionsDon&quot; , &quot;'&quot; , &quot;t have a company account?RegisterCopyright 2020 ©  PT Smooets Teknologi Outsourcing&quot;))]</value>
      <webElementGuid>0e3f417b-f994-4185-b6b8-1f28ba14ac7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
